import = [
    "~/Dotfiles/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# [colors]
# transparent_background_colors = true

decorations = "None"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
offset.x = 0  # For letter spacing (default: 0)
offset.y = 1  # For line spacing (default: 0)

size = 9
