
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "none"
opacity = 0.8  # Adjust transparency (0.0 is fully transparent, 1.0 is fully opaque)

[font]
normal.family = "MesloLGS Nerd Font Mono"
offset.x = 0
offset.y = 1
size = 9

[general]
import = [
    "~/Dotfiles/alacritty/tokyonight_night.toml"
]
