[[entry]]
played_at = "2026-08-24T14:02:44Z"
path = "/home/atiladefreitas/Music/Low Roar/Once in a Long, Long While… (2017)/01 - Don’t Be so Serious.mp3"
title = "Don’t Be so Serious"
artist = "Low Roar"
album = "Once in a Long, Long While…"
genre = "Dream Pop"
year = 2017
track_number = 1

[[entry]]
played_at = "2026-08-18T12:02:05Z"
path = "/home/atiladefreitas/Music/Linkin Park/Meteora (2003)/02 - Don't Stay.flac"
title = "Don't Stay"
artist = "Linkin Park"
album = "Meteora"
genre = "Alternative-Rock"
year = 2003
track_number = 2

[[entry]]
played_at = "2026-08-18T11:52:41Z"
path = "/home/atiladefreitas/Music/The Neighbourhood/Wiped Out! (2015)/05 - The Beach.flac"
title = "The Beach"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 5

[[entry]]
played_at = "2026-08-18T11:47:37Z"
path = "/home/atiladefreitas/Music/The Neighbourhood/Wiped Out! (2015)/04 - Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-07-20T18:45:51Z"
path = "/home/atiladefreitas/Music/The Neighbourhood/Wiped Out! (2015)/04 - Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-07-17T11:58:19Z"
path = "/home/atiladefreitas/Music/Low Roar/Once in a Long, Long While… (2017)/01 - Don’t Be so Serious.mp3"
title = "Don’t Be so Serious"
artist = "Low Roar"
album = "Once in a Long, Long While…"
genre = "Dream Pop"
year = 2017
track_number = 1

[[entry]]
played_at = "2026-07-15T15:38:29Z"
path = "/home/atiladefreitas/Music/The Neighbourhood/Wiped Out! (2015)/04 - Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-06-22T12:20:18Z"
path = "/home/atiladefreitas/Music/Low Roar/2017 ''Once In A Long, Long While''/04 Give Me an Answer.mp3"
title = "Give Me an Answer"
artist = "Low Roar"
album = "Once in a Long, Long While…"
genre = "Dream Pop"
year = 2017
track_number = 4

[[entry]]
played_at = "2026-06-13T15:14:17Z"
path = "/home/atiladefreitas/Music/The Neighbourhood /2015 - Wiped Out!/04 -Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-06-12T18:11:27Z"
path = "/home/atiladefreitas/Music/The Neighbourhood /2015 - Wiped Out!/04 -Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-06-09T19:22:59Z"
path = "/home/atiladefreitas/Music/The Neighbourhood /2015 - Wiped Out!/04 -Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-05-29T17:24:45Z"
path = "/home/atiladefreitas/Music/The Neighbourhood /2015 - Wiped Out!/08 -Greetings From Califournia.flac"
title = "Greetings From Califournia"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 8

[[entry]]
played_at = "2026-05-29T12:13:21Z"
path = "/home/atiladefreitas/Music/The Neighbourhood /2015 - Wiped Out!/04 -Wiped Out!.flac"
title = "Wiped Out!"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 4

[[entry]]
played_at = "2026-05-28T18:07:35Z"
path = "/home/atiladefreitas/Music/Yebba/Dawn/08 Louie Bag (Feat. Smino).flac"
title = "Louie Bag"
artist = "YEBBA"
album = "Dawn"
genre = "Pop, Rock, Alternatif et Indé"
year = 2021
track_number = 8

[[entry]]
played_at = "2026-05-28T17:53:26Z"
path = "/home/atiladefreitas/Music/Yebba/Dawn/07 October Sky.flac"
title = "October Sky"
artist = "YEBBA"
album = "Dawn"
genre = "Pop, Rock, Alternatif et Indé"
year = 2021
track_number = 7

[[entry]]
played_at = "2026-05-28T16:54:24Z"
path = "/home/atiladefreitas/Music/Daft Punk/Discovery/06 Nightvision.mp3"
title = "Nightvision"
artist = "Daft Punk"
album = "Discovery"
genre = "House"
year = 2001
track_number = 6

[[entry]]
played_at = "2026-05-28T14:26:58Z"
path = "/home/atiladefreitas/Music/Daft Punk/Discovery/05 Crescendolls.mp3"
title = "Crescendolls"
artist = "Daft Punk"
album = "Discovery"
genre = "House"
year = 2001
track_number = 5

[[entry]]
played_at = "2026-05-27T12:14:17Z"
path = "/home/atiladefreitas/Music/The Neighbourhood /2015 - Wiped Out!/07 -Baby Came Home 2  Valentines.flac"
title = "Baby Came Home 2 / Valentines"
artist = "The Neighbourhood"
album = "Wiped Out!"
genre = "Indie Rock"
year = 2015
track_number = 7
