-- Plugin integration highlights
local M = {}

function M.get(c, opts)
  local bg = opts.transparent and c.none or c.bg
  local bg_dark = opts.transparent and c.none or c.bg_dark
  local bg_float = opts.transparent and c.none or c.bg_float

  return {
    -- ============== Telescope ==============
    TelescopeNormal           = { fg = c.fg, bg = bg_float },
    TelescopeBorder           = { fg = c.border_focus, bg = bg_float },
    TelescopePromptNormal     = { fg = c.fg, bg = c.bg_popup },
    TelescopePromptBorder     = { fg = c.border_focus, bg = c.bg_popup },
    TelescopePromptTitle      = { fg = c.bg, bg = c.blue_bright, bold = true },
    TelescopePromptPrefix     = { fg = c.purple, bg = c.bg_popup },
    TelescopePromptCounter    = { fg = c.fg_dim, bg = c.bg_popup },
    TelescopeResultsNormal    = { fg = c.fg_dim, bg = bg_float },
    TelescopeResultsBorder    = { fg = c.border, bg = bg_float },
    TelescopeResultsTitle     = { fg = c.bg, bg = c.purple, bold = true },
    TelescopePreviewNormal    = { fg = c.fg, bg = bg_float },
    TelescopePreviewBorder    = { fg = c.border, bg = bg_float },
    TelescopePreviewTitle     = { fg = c.bg, bg = c.green, bold = true },
    TelescopeMatching         = { fg = c.yellow_bright, bold = true },
    TelescopeSelection        = { fg = c.fg, bg = c.bg_highlight, bold = true },
    TelescopeSelectionCaret   = { fg = c.purple, bg = c.bg_highlight, bold = true },
    TelescopeMultiSelection   = { fg = c.cyan_bright, bg = c.bg_highlight },

    -- ============== Snacks (picker, dashboard, notifier, indent) ==============
    SnacksNormal              = { fg = c.fg, bg = bg_float },
    SnacksNormalNC            = { fg = c.fg_dim, bg = bg_float },
    SnacksWinBar              = { fg = c.blue_bright, bg = bg_float, bold = true },
    SnacksWinBarNC            = { fg = c.fg_dark, bg = bg_float },
    SnacksBackdrop            = { bg = c.bg_darker },

    -- Picker
    SnacksPicker              = { fg = c.fg, bg = bg_float },
    SnacksPickerBorder        = { fg = c.border_focus, bg = bg_float },
    SnacksPickerTitle         = { fg = c.bg, bg = c.blue_bright, bold = true },
    SnacksPickerInput         = { fg = c.fg, bg = c.bg_popup },
    SnacksPickerInputBorder   = { fg = c.border_focus, bg = c.bg_popup },
    SnacksPickerInputTitle    = { fg = c.bg, bg = c.purple, bold = true },
    SnacksPickerList          = { fg = c.fg_dim, bg = bg_float },
    SnacksPickerListBorder    = { fg = c.border, bg = bg_float },
    SnacksPickerPreview       = { fg = c.fg, bg = bg_float },
    SnacksPickerPreviewBorder = { fg = c.border, bg = bg_float },
    SnacksPickerPreviewTitle  = { fg = c.bg, bg = c.green, bold = true },
    SnacksPickerMatch         = { fg = c.yellow_bright, bold = true },
    SnacksPickerSelected      = { fg = c.cyan_bright, bold = true },
    SnacksPickerCursorLine    = { bg = c.bg_highlight },
    SnacksPickerDir           = { fg = c.blue_bright },
    SnacksPickerFile          = { fg = c.fg },
    SnacksPickerIcon          = { fg = c.purple },
    SnacksPickerKey           = { fg = c.cyan },
    SnacksPickerComment       = { fg = c.comment, italic = true },

    -- Dashboard
    SnacksDashboard           = { fg = c.fg, bg = bg },
    SnacksDashboardHeader     = { fg = c.blue_bright, bold = true },
    SnacksDashboardFooter     = { fg = c.purple, italic = true },
    SnacksDashboardDesc       = { fg = c.fg_dim },
    SnacksDashboardKey        = { fg = c.yellow_bright, bold = true },
    SnacksDashboardIcon       = { fg = c.cyan },
    SnacksDashboardTitle      = { fg = c.green_bright, bold = true },
    SnacksDashboardSpecial    = { fg = c.purple },

    -- Notifier
    SnacksNotifierInfo        = { fg = c.info, bg = bg_float },
    SnacksNotifierWarn        = { fg = c.warning, bg = bg_float },
    SnacksNotifierError       = { fg = c.error, bg = bg_float },
    SnacksNotifierDebug       = { fg = c.purple, bg = bg_float },
    SnacksNotifierTrace       = { fg = c.fg_dim, bg = bg_float },
    SnacksNotifierBorderInfo  = { fg = c.info, bg = bg_float },
    SnacksNotifierBorderWarn  = { fg = c.warning, bg = bg_float },
    SnacksNotifierBorderError = { fg = c.error, bg = bg_float },
    SnacksNotifierTitleInfo   = { fg = c.info, bold = true },
    SnacksNotifierTitleWarn   = { fg = c.warning, bold = true },
    SnacksNotifierTitleError  = { fg = c.error, bold = true },

    -- Indent
    SnacksIndent              = { fg = c.fg_gutter },
    SnacksIndentScope         = { fg = c.purple },
    SnacksIndent1             = { fg = "#3a3d52" },
    SnacksIndent2             = { fg = "#3d3a52" },
    SnacksIndent3             = { fg = "#3a4252" },
    SnacksIndent4             = { fg = "#3d4a52" },
    SnacksIndent5             = { fg = "#3a523a" },
    SnacksIndent6             = { fg = "#523d3a" },
    SnacksIndent7             = { fg = "#523a4a" },
    SnacksIndent8             = { fg = "#52523a" },

    -- ============== Lualine (general groups, the lualine theme handles modes) ==============
    -- (See theme module below for full lualine theme)

    -- ============== Bufferline ==============
    BufferLineFill                  = { bg = c.bg_tabline },
    BufferLineBackground            = { fg = c.fg_dark, bg = c.bg_tabline },
    BufferLineBufferVisible         = { fg = c.fg_dim, bg = c.bg_tabline },
    BufferLineBufferSelected        = { fg = c.blue_bright, bg = bg, bold = true, italic = false },
    BufferLineSeparator             = { fg = c.bg_tabline, bg = c.bg_tabline },
    BufferLineSeparatorVisible      = { fg = c.bg_tabline, bg = c.bg_tabline },
    BufferLineSeparatorSelected     = { fg = c.blue_bright, bg = bg },
    BufferLineIndicatorSelected     = { fg = c.blue_bright, bg = bg },
    BufferLineModified              = { fg = c.yellow, bg = c.bg_tabline },
    BufferLineModifiedVisible       = { fg = c.yellow, bg = c.bg_tabline },
    BufferLineModifiedSelected      = { fg = c.green_bright, bg = bg },
    BufferLineCloseButton           = { fg = c.fg_dark, bg = c.bg_tabline },
    BufferLineCloseButtonVisible    = { fg = c.fg_dark, bg = c.bg_tabline },
    BufferLineCloseButtonSelected   = { fg = c.red, bg = bg },
    BufferLineDuplicate             = { fg = c.fg_dark, bg = c.bg_tabline, italic = true },
    BufferLineDuplicateVisible      = { fg = c.fg_dim, bg = c.bg_tabline, italic = true },
    BufferLineDuplicateSelected     = { fg = c.blue, bg = bg, italic = true },
    BufferLineDiagnosticError       = { fg = c.error, bg = c.bg_tabline },
    BufferLineDiagnosticWarn        = { fg = c.warning, bg = c.bg_tabline },
    BufferLineDiagnosticInfo        = { fg = c.info, bg = c.bg_tabline },
    BufferLineDiagnosticHint        = { fg = c.hint, bg = c.bg_tabline },
    BufferLineDiagnosticErrorSelected = { fg = c.error, bg = bg, bold = true },
    BufferLineDiagnosticWarnSelected  = { fg = c.warning, bg = bg, bold = true },

    -- ============== GitSigns ==============
    GitSignsAdd               = { fg = c.git_add },
    GitSignsChange            = { fg = c.git_change },
    GitSignsDelete            = { fg = c.git_delete },
    GitSignsAddNr             = { fg = c.git_add },
    GitSignsChangeNr          = { fg = c.git_change },
    GitSignsDeleteNr          = { fg = c.git_delete },
    GitSignsAddLn             = { bg = c.diff_add },
    GitSignsChangeLn          = { bg = c.diff_change },
    GitSignsDeleteLn          = { bg = c.diff_delete },
    GitSignsCurrentLineBlame  = { fg = c.fg_dark, italic = true },
    GitSignsAddInline         = { bg = c.diff_add },
    GitSignsDeleteInline      = { bg = c.diff_delete },
    GitSignsChangeInline      = { bg = c.diff_change },

    -- ============== Which-key ==============
    WhichKey                  = { fg = c.purple, bold = true },
    WhichKeyGroup             = { fg = c.blue_bright, bold = true },
    WhichKeyDesc              = { fg = c.fg },
    WhichKeySeparator         = { fg = c.fg_dark },
    WhichKeyFloat             = { bg = bg_float },
    WhichKeyBorder            = { fg = c.border_focus, bg = bg_float },
    WhichKeyValue             = { fg = c.cyan, italic = true },
    WhichKeyTitle             = { fg = c.bg, bg = c.blue_bright, bold = true },
    WhichKeyIcon              = { fg = c.cyan },
    WhichKeyIconAzure         = { fg = c.blue_bright },
    WhichKeyIconBlue          = { fg = c.blue },
    WhichKeyIconCyan          = { fg = c.cyan },
    WhichKeyIconGreen         = { fg = c.green },
    WhichKeyIconGrey          = { fg = c.fg_dark },
    WhichKeyIconOrange        = { fg = c.orange },
    WhichKeyIconPurple        = { fg = c.purple },
    WhichKeyIconRed           = { fg = c.red },
    WhichKeyIconYellow        = { fg = c.yellow },

    -- ============== Neo-tree ==============
    NeoTreeNormal             = { fg = c.fg_dim, bg = bg_dark },
    NeoTreeNormalNC           = { fg = c.fg_dim, bg = bg_dark },
    NeoTreeEndOfBuffer        = { fg = bg_dark, bg = bg_dark },
    NeoTreeRootName           = { fg = c.blue_bright, bold = true },
    NeoTreeDirectoryName      = { fg = c.fg },
    NeoTreeDirectoryIcon      = { fg = c.blue },
    NeoTreeFileName           = { fg = c.fg_dim },
    NeoTreeFileIcon           = { fg = c.fg_dim },
    NeoTreeFileNameOpened     = { fg = c.purple, italic = true },
    NeoTreeIndentMarker       = { fg = c.fg_gutter },
    NeoTreeExpander           = { fg = c.fg_dark },
    NeoTreeSymbolicLinkTarget = { fg = c.cyan, italic = true },
    NeoTreeModified           = { fg = c.yellow, bold = true },
    NeoTreeGitAdded           = { fg = c.git_add },
    NeoTreeGitConflict        = { fg = c.red, bold = true },
    NeoTreeGitDeleted         = { fg = c.git_delete },
    NeoTreeGitIgnored         = { fg = c.fg_gutter, italic = true },
    NeoTreeGitModified        = { fg = c.git_change },
    NeoTreeGitUnstaged        = { fg = c.warning },
    NeoTreeGitUntracked       = { fg = c.purple_bright },
    NeoTreeGitStaged          = { fg = c.green_bright },
    NeoTreeFloatBorder        = { fg = c.border_focus, bg = bg_float },
    NeoTreeFloatTitle         = { fg = c.blue_bright, bg = bg_float, bold = true },
    NeoTreeTitleBar           = { fg = c.bg, bg = c.blue_bright, bold = true },
    NeoTreeCursorLine         = { bg = c.bg_highlight },
    NeoTreeWinSeparator       = { fg = c.border, bg = bg_dark },
    NeoTreeTabActive          = { fg = c.blue_bright, bg = bg_dark, bold = true },
    NeoTreeTabInactive        = { fg = c.fg_dark, bg = bg_dark },
    NeoTreeTabSeparatorActive = { fg = bg_dark, bg = bg_dark },
    NeoTreeTabSeparatorInactive = { fg = bg_dark, bg = bg_dark },

    -- nvim-tree (in case it's used)
    NvimTreeNormal            = { fg = c.fg_dim, bg = bg_dark },
    NvimTreeRootFolder        = { fg = c.blue_bright, bold = true },
    NvimTreeFolderIcon        = { fg = c.blue },
    NvimTreeFileIcon          = { fg = c.fg_dim },
    NvimTreeOpenedFile        = { fg = c.purple, italic = true },
    NvimTreeIndentMarker      = { fg = c.fg_gutter },
    NvimTreeGitDirty          = { fg = c.git_change },
    NvimTreeGitNew            = { fg = c.git_add },
    NvimTreeGitDeleted        = { fg = c.git_delete },

    -- ============== Indent-Blankline (ibl) ==============
    IblIndent                 = { fg = c.fg_gutter, nocombine = true },
    IblWhitespace             = { fg = c.fg_gutter, nocombine = true },
    IblScope                  = { fg = c.purple, nocombine = true },

    -- ============== Mini.nvim suite ==============
    -- mini.statusline modes
    MiniStatuslineModeNormal  = { fg = c.bg, bg = c.blue_bright, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg, bg = c.green_bright, bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg, bg = c.purple, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeOther   = { fg = c.bg, bg = c.cyan, bold = true },
    MiniStatuslineDevinfo     = { fg = c.fg_dim, bg = c.bg_statusline },
    MiniStatuslineFilename    = { fg = c.fg, bg = c.bg_statusline },
    MiniStatuslineFileinfo    = { fg = c.fg_dim, bg = c.bg_statusline },
    MiniStatuslineInactive    = { fg = c.fg_dark, bg = c.bg_statusline },

    -- mini.indentscope
    MiniIndentscopeSymbol     = { fg = c.purple },
    MiniIndentscopePrefix     = { nocombine = true },

    -- mini.cursorword
    MiniCursorword            = { underline = true },
    MiniCursorwordCurrent     = { underline = true },

    -- mini.diff
    MiniDiffSignAdd           = { fg = c.git_add },
    MiniDiffSignChange        = { fg = c.git_change },
    MiniDiffSignDelete        = { fg = c.git_delete },
    MiniDiffOverAdd           = { bg = c.diff_add },
    MiniDiffOverChange        = { bg = c.diff_change },
    MiniDiffOverDelete        = { bg = c.diff_delete },
    MiniDiffOverContext       = { bg = c.bg_highlight },

    -- mini.icons
    MiniIconsAzure            = { fg = c.blue_bright },
    MiniIconsBlue             = { fg = c.blue },
    MiniIconsCyan             = { fg = c.cyan },
    MiniIconsGreen            = { fg = c.green },
    MiniIconsGrey             = { fg = c.fg_dark },
    MiniIconsOrange           = { fg = c.orange },
    MiniIconsPurple           = { fg = c.purple },
    MiniIconsRed              = { fg = c.red },
    MiniIconsYellow           = { fg = c.yellow },

    -- mini.files
    MiniFilesBorder           = { fg = c.border_focus, bg = bg_float },
    MiniFilesBorderModified   = { fg = c.yellow, bg = bg_float },
    MiniFilesNormal           = { fg = c.fg_dim, bg = bg_float },
    MiniFilesTitle            = { fg = c.fg, bg = bg_float, bold = true },
    MiniFilesTitleFocused     = { fg = c.blue_bright, bg = bg_float, bold = true },
    MiniFilesDirectory        = { fg = c.blue, bold = true },
    MiniFilesFile             = { fg = c.fg_dim },
    MiniFilesCursorLine       = { bg = c.bg_highlight },

    -- mini.pick
    MiniPickBorder            = { fg = c.border_focus, bg = bg_float },
    MiniPickBorderText        = { fg = c.blue_bright, bg = bg_float, bold = true },
    MiniPickNormal            = { fg = c.fg, bg = bg_float },
    MiniPickPrompt            = { fg = c.purple, bg = bg_float, bold = true },
    MiniPickMatchCurrent      = { fg = c.fg, bg = c.bg_highlight, bold = true },
    MiniPickMatchMarked       = { fg = c.cyan_bright, bg = bg_float },
    MiniPickMatchRanges       = { fg = c.yellow_bright, bold = true },
    MiniPickHeader            = { fg = c.blue_bright, bold = true },

    -- ============== Noice ==============
    NoiceCmdline              = { fg = c.fg, bg = bg_float },
    NoiceCmdlinePopup         = { fg = c.fg, bg = bg_float },
    NoiceCmdlinePopupBorder   = { fg = c.border_focus, bg = bg_float },
    NoiceCmdlinePopupTitle    = { fg = c.blue_bright, bg = bg_float, bold = true },
    NoiceCmdlineIcon          = { fg = c.purple },
    NoiceCmdlineIconCmdline   = { fg = c.purple },
    NoiceCmdlineIconSearch    = { fg = c.yellow_bright },
    NoiceCmdlineIconLua       = { fg = c.blue_bright },
    NoiceCmdlineIconHelp      = { fg = c.green },
    NoiceCmdlineIconFilter    = { fg = c.cyan },
    NoiceCmdlinePopupBorderCmdline   = { fg = c.purple, bg = bg_float },
    NoiceCmdlinePopupBorderSearch    = { fg = c.yellow_bright, bg = bg_float },
    NoiceCmdlinePopupBorderLua       = { fg = c.blue_bright, bg = bg_float },
    NoiceCmdlinePopupBorderHelp      = { fg = c.green, bg = bg_float },
    NoiceCmdlinePopupBorderFilter    = { fg = c.cyan, bg = bg_float },
    NoiceConfirm              = { fg = c.fg, bg = bg_float },
    NoiceConfirmBorder        = { fg = c.border_focus, bg = bg_float },
    NoicePopup                = { fg = c.fg, bg = bg_float },
    NoicePopupBorder          = { fg = c.border, bg = bg_float },
    NoicePopupmenu            = { fg = c.fg, bg = bg_float },
    NoicePopupmenuBorder      = { fg = c.border, bg = bg_float },
    NoicePopupmenuMatch       = { fg = c.yellow_bright, bold = true },
    NoicePopupmenuSelected    = { fg = c.fg, bg = c.bg_highlight, bold = true },
    NoiceMini                 = { fg = c.fg_dim, bg = bg_float },
    NoiceLspProgressTitle     = { fg = c.blue_bright, bold = true },
    NoiceLspProgressClient    = { fg = c.purple },
    NoiceLspProgressSpinner   = { fg = c.cyan },
    NoiceVirtualText          = { fg = c.purple, italic = true },
    NoiceFormatProgressTodo   = { fg = c.fg_dark, bg = c.bg_dark },
    NoiceFormatProgressDone   = { fg = c.bg, bg = c.green },
    NoiceFormatEvent          = { fg = c.cyan },
    NoiceFormatKind           = { fg = c.purple },
    NoiceFormatTitle          = { fg = c.blue_bright, bold = true },

    -- nvim-cmp / blink
    CmpItemAbbr                  = { fg = c.fg },
    CmpItemAbbrDeprecated        = { fg = c.fg_dark, strikethrough = true },
    CmpItemAbbrMatch             = { fg = c.yellow_bright, bold = true },
    CmpItemAbbrMatchFuzzy        = { fg = c.yellow_bright, bold = true },
    CmpItemKindDefault           = { fg = c.fg_dim },
    CmpItemKindFunction          = { fg = c.blue },
    CmpItemKindMethod            = { fg = c.blue },
    CmpItemKindVariable          = { fg = c.fg },
    CmpItemKindClass             = { fg = c.yellow },
    CmpItemKindInterface         = { fg = c.yellow },
    CmpItemKindKeyword           = { fg = c.purple },
    CmpItemKindSnippet           = { fg = c.green_bright },
    CmpItemKindText              = { fg = c.fg_dim },
    CmpItemKindModule            = { fg = c.yellow },
    CmpItemKindProperty          = { fg = c.cyan_bright },
    CmpItemKindField             = { fg = c.cyan_bright },
    CmpItemKindConstant          = { fg = c.purple_bright },
    CmpItemKindConstructor       = { fg = c.yellow },
    CmpItemMenu                  = { fg = c.fg_dark, italic = true },

    BlinkCmpMenu                 = { fg = c.fg, bg = c.bg_popup },
    BlinkCmpMenuBorder           = { fg = c.border_focus, bg = c.bg_popup },
    BlinkCmpMenuSelection        = { fg = c.blue_bright, bg = c.bg_highlight, bold = true },
    BlinkCmpLabel                = { fg = c.fg },
    BlinkCmpLabelMatch           = { fg = c.yellow_bright, bold = true },
    BlinkCmpLabelDeprecated      = { fg = c.fg_dark, strikethrough = true },
    BlinkCmpDoc                  = { fg = c.fg, bg = bg_float },
    BlinkCmpDocBorder            = { fg = c.border, bg = bg_float },
    BlinkCmpKind                 = { fg = c.purple },
    BlinkCmpSignatureHelp        = { fg = c.fg, bg = bg_float },
    BlinkCmpSignatureHelpBorder  = { fg = c.border_focus, bg = bg_float },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.yellow_bright, bold = true, underline = true },

    -- Trouble
    TroubleNormal             = { fg = c.fg_dim, bg = bg_dark },
    TroubleText               = { fg = c.fg_dim },
    TroubleCount              = { fg = c.purple, bg = c.bg_highlight },
    TroubleSource             = { fg = c.fg_dark, italic = true },
    TroubleFile               = { fg = c.blue_bright, bold = true },
    TroubleFoldIcon           = { fg = c.fg_dark },
    TroublePos                = { fg = c.cyan },
    TroubleIndent             = { fg = c.fg_gutter },

    -- Lazy.nvim
    LazyNormal                = { fg = c.fg, bg = bg_float },
    LazyButton                = { fg = c.fg, bg = c.bg_highlight },
    LazyButtonActive          = { fg = c.bg, bg = c.blue_bright, bold = true },
    LazyH1                    = { fg = c.bg, bg = c.purple, bold = true },
    LazySpecial               = { fg = c.cyan },
    LazyProgressDone          = { fg = c.green_bright, bold = true },
    LazyProgressTodo          = { fg = c.fg_gutter },
  }
end

return M
